secretagent:

  systemprompt:
    name: 'CV'
    file_sources:
      - AGENTS.md

  model:
    url: 'http://localhost:11434'
    name: 'qwen3.5' # disable thinking, temp 0.55 top_k 20
    num_ctx: 32768
    temperature: 0.55
    top_k: 20
    top_p: 0.95
    minp: 0.00
    thinking: false
    timeout_seconds: 120

  skills:
    dir: ./skills

  chatmemory:
    max_history_messages: 200
    auto_compact: false
