# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  IN: cv.typ
  OUT: cv-michel_de_bree.pdf
  VERSION:
    sh: git rev-parse --short HEAD

tasks:

  version:
    desc: Generate version.toml with git commit hash
    cmds:
      - echo "Version = \"{{.VERSION}}\"" > version.toml

  build:
    desc: Compile Typst document and optimize PDF
    deps:
      - version
    cmds:
      - typst compile {{.IN}} {{.OUT}}
      - pdfcpu optimize {{.OUT}}

  test:
    desc: Preview Typst with Tinymist
    cmds:
      - tinymist preview {{.IN}} --partial-rendering true

  watch:
    desc: Open PDF and watch Typst source for changes
    deps:
      - build
    cmds:
      - open {{.OUT}}
      - typst watch {{.IN}}

  deps:
    desc: Install project dependencies
    cmds:
      - brew bundle
      - mise up

  clean:
    desc: Remove generated PDFs
    cmds:
      - rm *.pdf
